@echo off
echo Instalando dependencias...
npm install
echo Generando Prisma...
npm run prisma:generate
echo Migrando base de datos...
npm run prisma:migrate
echo Ejecutando seed...
npm run prisma:seed
echo Iniciando servidor...
npm run dev